### ISSUE TITLE
Ability to set non-string values

### ISSUE THREAD

**Issue by paul-hansen** [ceejbot/tomato#2]
Thanks for making this crate, it's almost exactly what I was looking for.

Currently
```shell
tomato set language-server.rust-analyzer.config.cargo.noDefaultFeatures true ./.helix/languages.toml
```
Results in:
```toml
[language-server.rust-analyzer.config.cargo]
noDefaultFeatures = "true"
```

Note that true is a string not a boolean value. Ideally if I don't provide quotes around the value it would try to parse boolean, int and floats from the value and fallback to being a string if it isn't one of those types. Supporting [times](https://toml.io/en/v1.0.0#local-date-time) would be nice too for completeness, but possibly more work and not near as common as the others.
